### ISSUE TITLE
Enhanced User Access Management

### ISSUE THREAD

**Issue by sohagmahamud** [cloudcampbd/cloudninja#15]
We need to implement 3.1. Enhanced User Access Management feature for our application.

**Comment by engemamhosain** [comment]
temporary  app url http://54.87.54.161:8000/

**Comment by sohagmahamud** [comment]
@engemamhosain Excellent job! Could you kindly incorporate documentation, including the code, into a new branch titled "Enhanced User Management"? The documentation should encompass your approach, the decisions you've made, and the steps taken to implement all the functionalities within this section.
